apiVersion: v2
name: kavita
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "0.5.0"
kubeVersion: ">=1.16.0-0"
keywords:
  - ebooks
  - comics
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/kavita
icon: https://raw.githubusercontent.com/Kareadita/Kavita/develop/Logo/kavita.svg
sources:
  - https://github.com/Kareadita/Kavita 
maintainers:
  - name: sbilo 
    email: sander.bilo@gmail.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
